"""Add feedback to SkillRequest

Revision ID: 26c79be61294
Revises: 6182e278da76
Create Date: 2025-06-24 12:22:40.366430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c79be61294'
down_revision = '6182e278da76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_requests', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
