"""Initial migration

Revision ID: 6182e278da76
Revises: c0f2af6f4097
Create Date: 2025-06-23 16:42:17.250026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6182e278da76'
down_revision = 'c0f2af6f4097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_requests', schema=None) as batch_op:
        batch_op.alter_column('requester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('skill_requests', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('requester_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
